---
title: "CPU/Memory Performance Comparison"
author: "Gerry Tonkin-Hill"
date: "`r Sys.Date()`"
output: 
  html_document:
    fig_width: 12
    fig_height: 8
editor_options: 
  chunk_output_type: console
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(fig.width=20, fig.height=12,
                      echo=TRUE, warning=FALSE, message=FALSE,
                      tidy=TRUE)
options(stringsAsFactors = FALSE)
```

##Load libraries

```{r, warning=FALSE, message=FALSE}
library(ggplot2)
library(data.table)
library(readr)
library(purrr)
library(RColorBrewer)
library(stringr)
library(patchwork)
```

###Load data from log files

```{r}
get_cpu_mem <- function(filename){
  method <- unlist(str_split(gsub("0\\..*", "0", gsub(".*logs/", "", filename)), "_"))
  lines <- read_lines(filename)
  user_time <- as.numeric(tail(unlist(str_split(lines[grepl(".*User time .*", lines)], "\\s+")), n=1))
  sys_time <- as.numeric(tail(unlist(str_split(lines[grepl(".*System time .*", lines)], "\\s+")), n=1))
  mem <- as.numeric(tail(unlist(str_split(lines[grepl(".*Maximum resident set size .*", lines)], "\\s+")), n=1))*1e-3
  return(data.frame(method=method[[1]], 
                    db_size=as.numeric(tail(method, 1)), 
                    cpu_time=user_time+sys_time, 
                    memory=mem, 
                    stringsAsFactors = FALSE))
}

cpu_mem_df <- map_dfr(Sys.glob("timing_logs/*"), ~ get_cpu_mem(.x))
cpu_mem_df$db_label <- paste(cpu_mem_df$db_size, "isolates")
```

###Plot CPU usage

```{r}
ggplot(cpu_mem_df, aes(x=method, y=cpu_time)) + 
  geom_col() +
  facet_wrap(~db_label, nrow = 1) +
  scale_y_log10() +
  theme_bw(base_size = 14) +
  ylab("cpu time (seconds)")
```

###Plot Memory usage

```{r}
ggplot(cpu_mem_df, aes(x=method, y=memory)) + 
  geom_col() +
  facet_wrap(~db_label, nrow = 1) +
  scale_y_log10() +
  theme_bw(base_size = 14) +
  ylab("memory (Mb)")
```




